version: "3.8"

services:
  rmq:
    image: rabbitmq:3-management
    container_name: rmq
    restart: always
    volumes:
      - rmq:/etc/rmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '15672:15672'
      - '25672:5672'
    networks:
      - rmq

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongo

networks:
  rmq:


volumes:
  mongodata:
  rmq:
